package main

import (
	"cmdata2db/internal/app"
	"cmdata2db/internal/middleware"

	// docs are generated by Swag CLI, you have to import it.
	_ "cmdata2db/docs"
)

// @title 工单数据处理服务API
// @version 1.0.0
// @host localhost:8080
// @BasePath /
func main() {
	middleware.GetLogger().Info("服务启动成功")
	app.Start()
}
